import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
src/hc32_ll.c
src/hc32_ll_aos.c
src/hc32_ll_clk.c
src/hc32_ll_dma.c
src/hc32_ll_efm.c
src/hc32_ll_fcg.c
src/hc32_ll_fcm.c
src/hc32_ll_gpio.c
src/hc32_ll_icg.c
src/hc32_ll_interrupts.c
src/hc32_ll_pwc.c
src/hc32_ll_rmu.c
src/hc32_ll_utility.c
''')

if GetDepend(['RT_USING_SERIAL']):
    src += ['src/hc32_ll_usart.c']
    src += ['src/hc32_ll_tmr0.c']

if GetDepend(['RT_USING_I2C']):
    src += ['src/hc32_ll_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['src/hc32_ll_spi.c']

if GetDepend(['RT_USING_QSPI']):
    src += ['src/hc32_ll_qspi.c']

if GetDepend(['RT_USING_CAN']):
    src += ['src/hc32_ll_can.c']

if GetDepend(['RT_USING_ADC']):
    src += ['src/hc32_ll_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['src/hc32_ll_dac.c']

if GetDepend(['RT_USING_RTC']):
    src += ['src/hc32_ll_rtc.c']

if GetDepend(['RT_USING_WDT']):
    src += ['src/hc32_ll_swdt.c']
    src += ['src/hc32_ll_wdt.c']

if GetDepend(['RT_USING_ON_CHIP_FLASH']):
    src += ['src/hc32_ll_efm.c']

if GetDepend(['RT_USING_CLOCK_TIMER']):
    src += ['src/hc32_ll_tmr4.c']
    src += ['src/hc32_ll_tmr6.c']
    src += ['src/hc32_ll_tmra.c']

if GetDepend(['RT_USING_PULSE_ENCODER']):
    src += ['src/hc32_ll_tmr6.c']
    src += ['src/hc32_ll_tmra.c']

if GetDepend(['RT_USING_PWM']):
    src += ['src/hc32_ll_tmr4.c']
    src += ['src/hc32_ll_tmr6.c']
    src += ['src/hc32_ll_tmra.c']

if GetDepend(['RT_USING_INPUT_CAPTURE']):
    src += ['src/hc32_ll_tmr6.c']

if GetDepend(['RT_HWCRYPTO_USING_RNG']):
    src += ['src/hc32_ll_trng.c']

if GetDepend(['RT_HWCRYPTO_USING_CRC']):
    src += ['src/hc32_ll_crc.c']

if GetDepend(['RT_HWCRYPTO_USING_AES']):
    src += ['src/hc32_ll_aes.c']

if GetDepend(['RT_HWCRYPTO_USING_SHA2']):
    src += ['src/hc32_ll_hash.c']

if GetDepend(['BSP_RTC_USING_XTAL32']) or GetDepend(['RT_USING_PM']):
    src += ['src/hc32_ll_fcm.c']

if GetDepend(['BSP_USING_USBD']) or GetDepend(['BSP_USING_USBH']):
    src += ['src/hc32_ll_usb.c']

path = [cwd + '/inc']

CPPDEFINES = ['USE_DDL_DRIVER']

group = DefineGroup('HC32F472-LL', src, depend = ['SOC_HC32F472PE'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
